name: Create or Update Repo

on:
    workflow_dispatch:
        inputs:
            repo_name:
              description: Name of the repo to create.
              required: true
              type: string
            is_public_repo:
              description: 'If unchecked, repo is private'
              required: true
              default: false
              type: boolean
            package_import_name:
              description: Used in imports, e.g. `from <name> import ....`
              required: true
              type: string
env:
  GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}

jobs:
    create-repo-if-not-exists:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth:
          - env:
              REPO_NAME: ${{ github.event.inputs.repo_name }}
              GITHUB_USERNAME: Himans-Sys
              IS_PUBLIC_REPO: ${{ github.event.inputs.is_public_repo }}
              GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
            run: |
              gh auth status
              gh auth refresh -h github.com -t $GH_TOKEN
              bash run.sh create-repo-if-not-exist

    configure-repo:
        needs: [create-repo-if-not-exists]
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - run: |
              bash run.sh configure-repo
            env:
              TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
              PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
              REPO_NAME: ${{ github.event.inputs.repo_name }}
              GITHUB_USERNAME: Himans-Sys

    open-pr-with-generated-project:
        needs: [create-repo-if-not-exists]
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - env:
              TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
              PROD_PYPI_TOKEN: ${{ secrets.PROD_PYPI_TOKEN }}
              REPO_NAME: ${{ github.event.inputs.repo_name }}
              GITHUB_USERNAME: Himans-Sys
              PACKAGE_IMPORT_NAME: ${{ github.event.inputs.package_import_name }}
            run: |
              bash run.sh open-pr-with-generated-project
